name: clickable
description: Clickable components with cascading parameters for report
version: 0.0.11
homepage: https://github.com/songfei/flutter_clickable

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: